import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'data-tabular': ['Inter', 'sans-serif'],
                'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
                'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
                'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
            },
            fontSize: {
                'data-tabular': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '400' }],
                'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
            },
            colors: {
                'surface': '#f8f9ff',
                'on-secondary-fixed': '#002113',
                'on-tertiary-fixed-variant': '#3f465c',
                'tertiary-fixed': '#dae2fd',
                'secondary-fixed': '#6ffbbe',
                'on-tertiary-fixed': '#131b2e',
                'on-surface-variant': '#464555',
                'on-primary-fixed': '#0f0069',
                'tertiary-container': '#586076',
                'surface-container': '#e5eeff',
                'secondary': '#006c49',
                'on-error': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-variant': '#d3e4fe',
                'error': '#ba1a1a',
                'on-secondary-container': '#00714d',
                'on-primary-fixed-variant': '#3323cc',
                'on-surface': '#0b1c30',
                'on-background': '#0b1c30',
                'inverse-surface': '#213145',
                'surface-tint': '#4d44e3',
                'primary-container': '#4f46e5',
                'inverse-on-surface': '#eaf1ff',
                'surface-bright': '#f8f9ff',
                'tertiary': '#41485e',
                'background': '#f8f9ff',
                'on-tertiary-container': '#d4dbf5',
                'inverse-primary': '#c3c0ff',
                'secondary-container': '#6cf8bb',
                'tertiary-fixed-dim': '#bec6e0',
                'on-secondary-fixed-variant': '#005236',
                'secondary-fixed-dim': '#4edea3',
                'surface-dim': '#cbdbf5',
                'surface-container-high': '#dce9ff',
                'on-secondary': '#ffffff',
                'error-container': '#ffdad6',
                'on-tertiary': '#ffffff',
                'primary-fixed-dim': '#c3c0ff',
                'primary': '#3525cd',
                'on-primary-container': '#dad7ff',
                'outline-variant': '#c7c4d8',
                'on-error-container': '#93000a',
                'primary-fixed': '#e2dfff',
                'surface-container-highest': '#d3e4fe',
                'outline': '#777587',
                'surface-container-lowest': '#ffffff',
                'on-primary': '#ffffff',
                'secondary-fixed-variant': '#4edea3',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
                full: '0.75rem',
            },
            spacing: {
                'container-max': '1440px',
                'margin-mobile': '16px',
                'gutter': '24px',
                'stack-md': '16px',
                'margin-desktop': '32px',
                'stack-lg': '32px',
                'unit': '4px',
                'stack-sm': '8px',
            },
            maxWidth: {
                'container-max': '1440px',
            },
        },
    },

    plugins: [forms],
};
